networks:
  studymate-network:
    external: true
    name: study_mate_ai_studymate-network

services:

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    environment:
      AUTH_DB_URL: postgresql://auth_user:auth_pass@postgres-auth:5432/auth_db
      JWT_SECRET: supersecretjwtkey123
      JWT_ALGORITHM: HS256
      JWT_EXPIRE_MINUTES: 60
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8101:8001"
    networks:
      - studymate-network
  api-gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8000:80"
    networks:
      - studymate-network
    depends_on:
      - auth-service
      - material-service
      - memory-service
      - ai-service
      - multi-agent

  material-service:
    build: ./services/material-service
    container_name: material-service
    environment:
      MATERIAL_DB_URL: postgresql://material_user:material_pass@postgres-material:5432/material_db
      MINIO_URL: minio:9000
      MINIO_ACCESS_KEY: minio_user
      MINIO_SECRET_KEY: minio_pass
      MINIO_BUCKET: study-materials
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      AUTH_SERVICE_URL: http://auth-service:8001
    ports:
      - "8102:8002"
    networks:
      - studymate-network
    depends_on:
      - auth-service

  memory-service:
    build: ./services/memory-service
    container_name: memory-service
    environment:
      MONGODB_URL: mongodb://mongo_user:mongo_pass@mongodb:27017/memory_db?authSource=admin
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      AUTH_SERVICE_URL: http://auth-service:8001
    ports:
      - "8104:8004"
    networks:
      - studymate-network
    depends_on:
      - auth-service

  ai-service:
    build: ./services/ai-service
    container_name: ai-service
    environment:
      QDRANT_URL: http://qdrant:6333
      OLLAMA_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: qwen2.5
      MEMORY_SERVICE_URL: http://memory-service:8004
      AUTH_SERVICE_URL: http://auth-service:8001
      REDIS_URL: redis://redis:6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LANGFUSE_PUBLIC_KEY: pk-lf-placeholder
      LANGFUSE_SECRET_KEY: sk-lf-placeholder
      LANGFUSE_HOST: http://langfuse:3000
    ports:
      - "8103:8003"
    networks:
      - studymate-network
    depends_on:
      - memory-service
      - auth-service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  multi-agent:
    build: ./agents/multi-agent
    container_name: multi-agent
    environment:
      OLLAMA_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: qwen2.5
      QDRANT_URL: http://qdrant:6333
      MEMORY_SERVICE_URL: http://memory-service:8004
      AUTH_SERVICE_URL: http://auth-service:8001
      LANGFUSE_PUBLIC_KEY: pk-lf-placeholder
      LANGFUSE_SECRET_KEY: sk-lf-placeholder
      LANGFUSE_HOST: http://langfuse:3000
      COLLECTION_NAME: study_materials
    ports:
      - "8110:8010"
    networks:
      - studymate-network
    depends_on:
      - memory-service
      - auth-service
    extra_hosts:
      - "host.docker.internal:host-gateway"