apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
  namespace: studymate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: "auth_db"
            - name: POSTGRES_USER
              value: "auth_user"
            - name: POSTGRES_PASSWORD
              value: "auth_pass"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: studymate
spec:
  selector:
    app: postgres-auth
  ports:
    - port: 5432
      targetPort: 5432
