apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-material
  namespace: studymate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-material
  template:
    metadata:
      labels:
        app: postgres-material
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: "material_db"
            - name: POSTGRES_USER
              value: "material_user"
            - name: POSTGRES_PASSWORD
              value: "material_pass"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-material
  namespace: studymate
spec:
  selector:
    app: postgres-material
  ports:
    - port: 5432
      targetPort: 5432
