apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: studymate
type: Opaque
stringData:
  db-url: "postgresql://auth_user:auth_pass@postgres-auth:5432/auth_db"
  jwt-secret: "supersecretjwtkey123"